title: "NB6G Amateur Radio"
description: "Personal amateur radio website"
url: "https://nb6g.github.io"
baseurl: ""

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

exclude:
  - README.md
