title: "NB6G Amateur Radio"
description: "Personal amateur radio website"
url: "https://douglasyu.net"
baseurl: "/nb6g"

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

exclude:
  - README.md
